import { expect, mock, test } from 'claude-code/testing'
import { stubEngine, run, mountPane, board } from './test-support'
test('指令開啟自己的棋盤、下一塊與初始統計', async ($, on) => {
  stubEngine(on)
  mock.clock(on)
  expect((await run($))!.text).toContain('已開啟')
  const ui = await mountPane($)
  const raster = await ui.find({ key: 'board' })
  expect(raster!.props.columns).toBe(20)
  expect(raster!.props.rows).toBe(20)
  expect(await board(ui)).toEqual(Array(20).fill('..........'))
  expect(await ui.find({ type: 'Text', text: /^下一塊：/ })).toBeDefined()
  expect((await ui.find({ type: 'Text', text: '分數：0' }))!.text).toBe('分數：0')
  expect((await ui.find({ type: 'Text', text: '消行：0' }))!.text).toBe('消行：0')
  expect((await ui.find({ type: 'Text', text: '等級：0' }))!.text).toBe('等級：0')
})
test('玩家能下移並左右移動出生區的 L 方塊', async ($, on) => {
  stubEngine(on); mock.clock(on)
  await run($); const ui = await mountPane($)
  for (let i = 0; i < 3; i++) await ui.press({ key: 'down' })
  await ui.press({ key: 'left' })
  expect((await board(ui)).slice(1, 3)).toEqual(['...LLL....', '...L......'])
  await ui.press({ key: 'right' })
  expect((await board(ui)).slice(1, 3)).toEqual(['....LLL...', '....L.....'])
})
test('旋轉 L 方塊採原版逆時針規則', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 3; i++) await ui.press({ key: 'down' })
  await ui.press({ key: 'rotate' })
  expect((await board(ui)).slice(0, 3)).toEqual(['.....L....', '.....L....', '.....LL...'])
})
test('牆壁與地板拒絕越界', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 25; i++) await ui.press({ key: 'down' })
  for (let i = 0; i < 15; i++) await ui.press({ key: 'left' })
  expect((await board(ui)).slice(-2)).toEqual(['LLL.......', 'L.........'])
  const before = await board(ui)
  await ui.press({ key: 'down' }); await ui.press({ key: 'left' })
  expect(await board(ui)).toEqual(before)
  for (let i = 0; i < 15; i++) await ui.press({ key: 'right' })
  expect((await board(ui)).slice(-2)).toEqual(['.......LLL', '.......L..'])
})
test('旋轉在左牆嘗試右移一格修正', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 4; i++) await ui.press({ key: 'down' })
  await ui.press({ key: 'rotate' }); await ui.press({ key: 'rotate' }); await ui.press({ key: 'rotate' })
  for (let i = 0; i < 10; i++) await ui.press({ key: 'left' })
  await ui.press({ key: 'rotate' })
  expect((await board(ui)).slice(2, 4)).toEqual(['LLL.......', 'L.........'])
})
test('按鈕顯示 WASD 的快捷鍵', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($)
  for (const [key, hotkey] of [['left','a'], ['right','d'], ['rotate','w'], ['down','s']]) expect((await ui.find({ key }))!.props.hotkey).toBe(hotkey)
})
test('I 在兩個方向切換，地板阻擋旋轉時拒絕', async ($, on) => {
  stubEngine(on); mock.clock(on, { now: 36 }); await run($); const ui = await mountPane($)
  for (let i = 0; i < 5; i++) await ui.press({ key: 'down' })
  const before = await board(ui)
  await ui.press({ key: 'rotate' })
  expect((await board(ui)).slice(2, 6)).toEqual(['.....I....', '.....I....', '.....I....', '.....I....'])
  await ui.press({ key: 'rotate' })
  expect(await board(ui)).toEqual(before)
  for (let i = 0; i < 25; i++) await ui.press({ key: 'down' })
  const floor = await board(ui)
  await ui.press({ key: 'rotate' })
  expect(await board(ui)).toEqual(floor)
})
test('O 方塊旋轉不改變位置', async ($, on) => {
  stubEngine(on); mock.clock(on, { now: 129 }); await run($); const ui = await mountPane($)
  for (let i = 0; i < 4; i++) await ui.press({ key: 'down' })
  const before = await board(ui)
  expect(before.slice(2, 4)).toEqual(['....OO....','....OO....'])
  await ui.press({ key: 'rotate' }); expect(await board(ui)).toEqual(before)
})
test('旋轉在右牆嘗試左移一格修正', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 4; i++) await ui.press({ key: 'down' })
  await ui.press({ key: 'rotate' })
  for (let i = 0; i < 10; i++) await ui.press({ key: 'right' })
  await ui.press({ key: 'rotate' })
  expect((await board(ui)).slice(1, 3)).toEqual(['.........L','.......LLL'])
})
test('原版首次 tick 立即推進，其後每 400ms 下落一格', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); await clock.settle(); const ui = await mountPane($)
  await clock.advance(400)
  expect((await board(ui))[0]).toBe('....LLL...')
  await clock.advance(399); expect((await board(ui))[0]).toBe('....LLL...')
  await clock.advance(1); expect((await board(ui)).slice(1, 3)).toEqual(['....LLL...', '....L.....'])
})
test('落地後下一 tick 固定，預覽換成活動塊且不能穿越堆疊', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 25; i++) await ui.press({ key: 'down' })
  expect((await ui.find({ type: 'Text', text: /^下一塊：/ }))!.text).toBe('下一塊：O')
  await clock.settle()
  expect((await ui.find({ type: 'Text', text: /^下一塊：/ }))!.text).toBe('下一塊：T')
  for (let i = 0; i < 25; i++) await ui.press({ key: 'down' })
  expect((await board(ui)).slice(-4)).toEqual(['....OO....', '....OO....', '....LLL...', '....L.....'])
})
test('直接落底鎖住操作與暫停，下一 tick 才固定', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); const ui = await mountPane($)
  await ui.press({ key: 'drop' })
  expect((await board(ui)).slice(-2)).toEqual(['....LLL...', '....L.....'])
  expect(await ui.find({ type: 'Text', text: '正在固定（下一 tick）' })).toBeDefined()
  const before = await board(ui)
  for (const key of ['left','right','down','rotate','pause','drop']) await ui.press({ key })
  expect(await board(ui)).toEqual(before)
  await clock.settle()
  expect((await ui.find({ type: 'Text', text: /^下一塊：/ }))!.text).toBe('下一塊：T')
})
test('暫停與重新開始保留暫停，繼續後不補跑時間', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); await clock.settle(); const ui = await mountPane($)
  await ui.press({ key: 'pause' })
  const before = await board(ui)
  await ui.press({ key: 'left' }); await clock.advance(2000)
  expect(await board(ui)).toEqual(before)
  expect(await ui.find({ type: 'Text', text: '已暫停' })).toBeDefined()
  await ui.press({ key: 'restart' })
  expect(await ui.find({ type: 'Text', text: '已暫停' })).toBeDefined()
  const restarted = await board(ui)
  await clock.advance(2000); expect(await board(ui)).toEqual(restarted)
  expect(await ui.find({ type: 'Text', text: '分數：0' })).toBeDefined()
  await ui.press({ key: 'pause' })
  await clock.advance(399); expect(await board(ui)).toEqual(restarted)
  await clock.advance(1); await clock.advance(400); expect(await board(ui)).not.toEqual(restarted)
})
