import { expect, mock, test } from 'claude-code/testing'
import { stubEngine, run, mountPane, board, place, SINGLE_STEPS, LONG_STEPS, rasterCells } from './test-support'
test('指令開啟自己的棋盤、下一塊與初始統計', async ($, on) => {
  stubEngine(on)
  mock.clock(on)
  expect((await run($))!.text).toContain('已開啟')
  const ui = await mountPane($)
  const raster = await ui.find({ key: 'board' })
  expect(raster!.props.columns).toBe(20)
  expect(raster!.props.rows).toBe(20)
  expect(await board(ui)).toEqual(Array(20).fill('..........'))
  expect(await ui.find({ type: 'Text', text: /^下一塊：/ })).toBeDefined()
  expect((await ui.find({ type: 'Text', text: '分數：0' }))!.text).toBe('分數：0')
  expect((await ui.find({ type: 'Text', text: '消行：0' }))!.text).toBe('消行：0')
  expect((await ui.find({ type: 'Text', text: '等級：0' }))!.text).toBe('等級：0')
})
test('玩家能下移並左右移動出生區的 L 方塊', async ($, on) => {
  stubEngine(on); mock.clock(on)
  await run($); const ui = await mountPane($)
  for (let i = 0; i < 3; i++) await ui.press({ key: 'down' })
  await ui.press({ key: 'left' })
  expect((await board(ui)).slice(1, 3)).toEqual(['...LLL....', '...L......'])
  await ui.press({ key: 'right' })
  expect((await board(ui)).slice(1, 3)).toEqual(['....LLL...', '....L.....'])
})
test('旋轉 L 方塊採原版逆時針規則', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 3; i++) await ui.press({ key: 'down' })
  await ui.press({ key: 'rotate' })
  expect((await board(ui)).slice(0, 3)).toEqual(['.....L....', '.....L....', '.....LL...'])
})
test('牆壁與地板拒絕越界', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 25; i++) await ui.press({ key: 'down' })
  for (let i = 0; i < 15; i++) await ui.press({ key: 'left' })
  expect((await board(ui)).slice(-2)).toEqual(['LLL.......', 'L.........'])
  const before = await board(ui)
  await ui.press({ key: 'down' }); await ui.press({ key: 'left' })
  expect(await board(ui)).toEqual(before)
  for (let i = 0; i < 15; i++) await ui.press({ key: 'right' })
  expect((await board(ui)).slice(-2)).toEqual(['.......LLL', '.......L..'])
})
test('旋轉在左牆嘗試右移一格修正', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 4; i++) await ui.press({ key: 'down' })
  await ui.press({ key: 'rotate' }); await ui.press({ key: 'rotate' }); await ui.press({ key: 'rotate' })
  for (let i = 0; i < 10; i++) await ui.press({ key: 'left' })
  await ui.press({ key: 'rotate' })
  expect((await board(ui)).slice(2, 4)).toEqual(['LLL.......', 'L.........'])
})
test('按鈕顯示 WASD 的快捷鍵', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($)
  for (const [key, hotkey] of [['left','a'], ['right','d'], ['rotate','w'], ['down','s']]) expect((await ui.find({ key }))!.props.hotkey).toBe(hotkey)
})
test('I 在兩個方向切換，地板阻擋旋轉時拒絕', async ($, on) => {
  stubEngine(on); mock.clock(on, { now: 36 }); await run($); const ui = await mountPane($)
  for (let i = 0; i < 5; i++) await ui.press({ key: 'down' })
  const before = await board(ui)
  await ui.press({ key: 'rotate' })
  expect((await board(ui)).slice(2, 6)).toEqual(['.....I....', '.....I....', '.....I....', '.....I....'])
  await ui.press({ key: 'rotate' })
  expect(await board(ui)).toEqual(before)
  for (let i = 0; i < 25; i++) await ui.press({ key: 'down' })
  const floor = await board(ui)
  await ui.press({ key: 'rotate' })
  expect(await board(ui)).toEqual(floor)
})
test('O 方塊旋轉不改變位置', async ($, on) => {
  stubEngine(on); mock.clock(on, { now: 129 }); await run($); const ui = await mountPane($)
  for (let i = 0; i < 4; i++) await ui.press({ key: 'down' })
  const before = await board(ui)
  expect(before.slice(2, 4)).toEqual(['....OO....','....OO....'])
  await ui.press({ key: 'rotate' }); expect(await board(ui)).toEqual(before)
})
test('旋轉在右牆嘗試左移一格修正', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 4; i++) await ui.press({ key: 'down' })
  await ui.press({ key: 'rotate' })
  for (let i = 0; i < 10; i++) await ui.press({ key: 'right' })
  await ui.press({ key: 'rotate' })
  expect((await board(ui)).slice(1, 3)).toEqual(['.........L','.......LLL'])
})
test('原版首次 tick 立即推進，其後每 400ms 下落一格', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); await clock.settle(); const ui = await mountPane($)
  await clock.advance(400)
  expect((await board(ui))[0]).toBe('....LLL...')
  await clock.advance(399); expect((await board(ui))[0]).toBe('....LLL...')
  await clock.advance(1); expect((await board(ui)).slice(1, 3)).toEqual(['....LLL...', '....L.....'])
})
test('落地後下一 tick 固定，預覽換成活動塊且不能穿越堆疊', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 25; i++) await ui.press({ key: 'down' })
  expect((await ui.find({ type: 'Text', text: /^下一塊：/ }))!.text).toBe('下一塊：O')
  await clock.settle()
  expect((await ui.find({ type: 'Text', text: /^下一塊：/ }))!.text).toBe('下一塊：T')
  for (let i = 0; i < 25; i++) await ui.press({ key: 'down' })
  expect((await board(ui)).slice(-4)).toEqual(['....OO....', '....OO....', '....LLL...', '....L.....'])
})
test('直接落底鎖住操作與暫停，下一 tick 才固定', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); const ui = await mountPane($)
  await ui.press({ key: 'drop' })
  expect((await board(ui)).slice(-2)).toEqual(['....LLL...', '....L.....'])
  expect(await ui.find({ type: 'Text', text: '正在固定（下一 tick）' })).toBeDefined()
  const before = await board(ui)
  for (const key of ['left','right','down','rotate','pause','drop']) await ui.press({ key })
  expect(await board(ui)).toEqual(before)
  await clock.settle()
  expect((await ui.find({ type: 'Text', text: /^下一塊：/ }))!.text).toBe('下一塊：T')
})
test('暫停與重新開始保留暫停，繼續後不補跑時間', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); await clock.settle(); const ui = await mountPane($)
  await ui.press({ key: 'pause' })
  const before = await board(ui)
  await ui.press({ key: 'left' }); await clock.advance(2000)
  expect(await board(ui)).toEqual(before)
  expect(await ui.find({ type: 'Text', text: '已暫停' })).toBeDefined()
  await ui.press({ key: 'restart' })
  expect(await ui.find({ type: 'Text', text: '已暫停' })).toBeDefined()
  const restarted = await board(ui)
  await clock.advance(2000); expect(await board(ui)).toEqual(restarted)
  expect(await ui.find({ type: 'Text', text: '分數：0' })).toBeDefined()
  await ui.press({ key: 'pause' })
  await clock.advance(399); expect(await board(ui)).toEqual(restarted)
  await clock.advance(1); await clock.advance(400); expect(await board(ui)).not.toEqual(restarted)
})

test('第 2 行填滿後消除一行，上方下移並加 40 分', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); const ui = await mountPane($)
  for (const step of SINGLE_STEPS) { await place(ui, step); await clock.advance(400) }
  expect(await ui.find({ type: 'Text', text: '消行：1' })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: '分數：40' })).toBeDefined()
  expect((await board(ui)).slice(-3)).toEqual(['........S.','.ZZ.TTTZSS','OOLLL.ZTTT'])
})

test('跨袋後消除四行，先以舊等級加分再升級，下一間隔為 289ms', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); const ui = await mountPane($)
  const shapes = ['L']
  for (let i = 0; i < 32; i++) {
    shapes.push((await ui.find({ type: 'Text', text: /^下一塊：/ }))!.text.slice(-1))
    await place(ui, LONG_STEPS[i]!); await clock.advance(400)
  }
  for (const shape of ['I','O','T','S','Z','J','L']) expect(shapes.slice(0, 28).filter(s => s === shape)).toHaveLength(4)
  expect(await ui.find({ type: 'Text', text: '消行：10' })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: '分數：1440' })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: '等級：1' })).toBeDefined()
  expect((await board(ui)).slice(-5)).toEqual(['.......J..','.....T.J..','.ZOOTTJJL.','ZZOOSTLLL.','ILJ.SSS.II'])
  await ui.press({ key: 'down' }); await ui.press({ key: 'down' }); await ui.press({ key: 'down' })
  const before = await board(ui)
  await clock.advance(288); expect(await board(ui)).toEqual(before)
  await clock.advance(1); expect(await board(ui)).not.toEqual(before)
})
test('同局二行、非相鄰三行與連續三行按當前等級計分並正確搬移', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 100; i++) {
    await place(ui, LONG_STEPS[i]!); await clock.advance(400)
    if (i === 33) {
      expect(await ui.find({ type: 'Text', text: '消行：12' })).toBeDefined()
      expect(await ui.find({ type: 'Text', text: '分數：1640' })).toBeDefined()
      expect((await board(ui)).slice(-3)).toEqual(['.Z.....J..','ZZ...T.JLL','ILJ.SSS.II'])
    }
    if (i === 77) {
      // 第 3、4、6 行一起刪除：第 5 行只下移兩格，不能當作三個相鄰行。
      expect(await ui.find({ type: 'Text', text: '消行：25' })).toBeDefined()
      expect(await ui.find({ type: 'Text', text: '分數：3520' })).toBeDefined()
      expect((await board(ui)).slice(-4)).toEqual(['TTZZ.T..OO','TT.JSLLIOO','ZZ.SSIJIOO','ZZ.SSIIIOO'])
    }
  }
  expect(await ui.find({ type: 'Text', text: '消行：35' })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: '分數：5700' })).toBeDefined()
  expect((await board(ui)).slice(-6)).toEqual(['...IT..JJJ','SSILJSSIZ.','TTZZJT.IOO','TT.JSLLIOO','ZZ.SSIJIOO','ZZ.SSIIIOO'])
})
test('累計 160 行仍維持內部等級 15 上限與原版間隔', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); const ui = await mountPane($)
  for (const step of LONG_STEPS) {
    await place(ui, step)
    const level = Number((await ui.find({ type: 'Text', text: /^等級：/ }))!.text.slice(3))
    // 依參考 ticker 的有效間隔送出下一次正常 tick，避免高等級多次下落改變輸入局面。
    await clock.advance(Math.floor(400000 * .85 ** (2 * level)) / 1000)
  }
  expect(await ui.find({ type: 'Text', text: '消行：160' })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: '等級：15' })).toBeDefined()
  await ui.press({ key: 'down' }); await ui.press({ key: 'down' }); await ui.press({ key: 'down' })
  const before = await board(ui)
  await clock.advance(3.051); expect(await board(ui)).toEqual(before)
  await clock.advance(.002); expect(await board(ui)).not.toEqual(before)
})
test('出生位置停止下落才結束，結束後停止操作與計時並可重開', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); const ui = await mountPane($)
  for (let i = 0; i < 18; i++) { await ui.press({ key: 'drop' }); await clock.advance(400) }
  expect(await ui.find({ type: 'Text', text: '遊戲結束' })).toBeDefined()
  const before = await board(ui)
  for (const key of ['left','right','down','rotate','drop','pause']) await ui.press({ key })
  await clock.advance(4000); expect(await board(ui)).toEqual(before)
  await ui.press({ key: 'restart' })
  expect(await ui.find({ type: 'Text', text: '遊戲中' })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: '分數：0' })).toBeDefined()
})
test('關閉面板仍推進，再開保留本局，暫停後關閉也保留暫停', async ($, on) => {
  const env = stubEngine(on); const clock = mock.clock(on); await run($); await clock.settle(); const ui = await mountPane($)
  expect((await run($)).text).toContain('已關閉'); expect(env.isOpen).toBe(false)
  await clock.advance(800)
  const before = await board(ui)
  expect(before.slice(1, 3)).toEqual(['....LLL...','....L.....'])
  expect((await run($)).text).toContain('已開啟'); expect(await board(ui)).toEqual(before)
  await ui.press({ key: 'pause' }); await run($); await clock.advance(1000); await run($)
  expect(await board(ui)).toEqual(before)
  expect(await ui.find({ type: 'Text', text: '已暫停' })).toBeDefined()
})
test('session 結束取消舊排程，重新載入入口恢復本局且只有一條重力', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on)
  on('session.end', (_$, e) => ({ sessionId: e.sessionId }))
  await run($); await clock.settle(); const ui = await mountPane($)
  const before = await board(ui)
  await $.session.end({ reason: 'clear', sessionId: 'test', resume: { id: 'test' } })
  await clock.advance(1200); expect(await board(ui)).toEqual(before)
  // 模擬 session.start 恢復入口；不宣稱此測試卸載了模組或重設了 session state。
  await $.session.start({ cwd: '/tmp', surface: 'terminal', isInteractive: true })
  await $.session.start({ cwd: '/tmp', surface: 'terminal', isInteractive: true })
  await clock.advance(400)
  expect((await board(ui))[0]).toBe('....LLL...')
})
test('空間不足時說明尺寸，仍能手動暫停而不自動暫停', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($, 18, 12)
  expect(await ui.find({ type: 'Text', text: /面板至少需要.*（目前 18 欄 × 12 列，dock）/ })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: '遊戲中' })).toBeDefined()
  await ui.press({ key: 'pause' })
  expect(await ui.find({ type: 'Text', text: '已暫停' })).toBeDefined()
})
test('最少列數等於版面實際高度：並排 20 列、直排 31 列、窄版 34 列', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($)
  for (const [columns, rows, fits] of [[42, 20, true], [42, 19, false], [41, 31, true], [41, 30, false], [30, 34, true], [30, 33, false]] as const) {
    const ui = await mountPane($, columns, rows)
    expect(await ui.find({ key: 'board' }) !== undefined).toBe(fits)
    expect(await ui.find({ type: 'Text', text: /面板至少需要/ }) !== undefined).toBe(!fits)
    await ui.unmount()
  }
})
test('下一塊預覽顯示 O 的二乘二形狀', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($); const ui = await mountPane($)
  expect(await ui.find({ type: 'Text', text: 'OOOO\nOOOO' })).toBeDefined()
})
test('session 識別改變時舊 ticker 不可寫入新 session', async ($, on) => {
  const env = stubEngine(on); const clock = mock.clock(on); await run($); await clock.settle(); const ui = await mountPane($)
  const before = await board(ui)
  // 模擬引擎的身分邊界變化，不直接設定遊戲 state；真實 /clear 另行驗收。
  env.sessionId = 'session-2'
  await clock.advance(1200)
  expect(await board(ui)).toEqual(before)
})
test('重新開始取消舊期限，反覆重畫不增生計時器', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await run($); await clock.settle(); const ui = await mountPane($)
  await clock.advance(200); await ui.press({ key: 'restart' })
  for (let i = 0; i < 4; i++) await ui.press({ key: 'down' })
  const before = await board(ui)
  await clock.advance(200); expect(await board(ui)).toEqual(before)
  await clock.advance(200); expect(await board(ui)).not.toEqual(before)
})
test('不支援 Raster 的 surface 顯示 CLI 提示', async ($, on) => {
  stubEngine(on); mock.clock(on); await run($)
  const ui = await $.ui.mount({ plugin: 'tetris', surface: 'desktop', component: 'Pane', requestId: 'tetris', props: { title: '俄羅斯方塊', isFocused: true, bodyColumns: 48, placement: 'dock', scroll: { offset: 0, bodyRows: 40 }, view: {} } })
  expect(await ui.find({ type: 'Text', text: /請在 Claude Code CLI/ })).toBeDefined()
  expect(await ui.find({ key: 'board' })).toBeUndefined()
})
test('只處理自己的 Pane，被其他分頁蓋住時可再開', async ($, on) => {
  const env = stubEngine(on); mock.clock(on)
  on('ui.render', { component: 'Pane', requestId: 'another' }, ($, e) => {
    const { Text } = $.ui.resolve(e); return Text({ children: '另一個面板' })
  })
  await run($); env.isShown = false
  expect((await run($)).text).toContain('已開啟')
  const ui = await $.ui.mount({ plugin: 'tetris', surface: 'terminal', component: 'Pane', requestId: 'another', props: { title: '另一個面板', isFocused: true, bodyColumns: 48, placement: 'dock', scroll: { offset: 0, bodyRows: 40 }, view: {} } })
  expect(await ui.find({ key: 'board' })).toBeUndefined()
  expect(await ui.find({ type: 'Text', text: '另一個面板' })).toBeDefined()
})

test('同形 L 的活動四格有不同背景，暫停時仍與固定格可辨', async ($, on) => {
  stubEngine(on); const clock = mock.clock(on); await clock.advance(2)
  await run($); const ui = await mountPane($)
  await ui.press({ key: 'drop' }); await clock.advance(400)
  for (let i = 0; i < 4; i++) await ui.press({ key: 'down' })
  const cells = await rasterCells(ui)
  const active = cells.slice(0, 50).filter(cell => cell.char === 'L')
  const fixed = cells.slice(50).filter(cell => cell.char === 'L')
  expect(active).toHaveLength(4)
  expect(fixed.length).toBeGreaterThan(0)
  expect(active[0]!.background).not.toBe(fixed[0]!.background)
  expect(active.every(cell => cell.background === active[0]!.background)).toBe(true)
  await ui.press({ key: 'pause' }); await clock.advance(1000)
  expect(await rasterCells(ui)).toEqual(cells)
})
